### ISSUE TITLE
Workers eventually stop working

### ISSUE THREAD

**Issue by carsoncole** [rails/solid_queue#204]
I seem to have a persistent problem of jobs being worked but new jobs just get enqueued and workers stop pulling jobs to be worked. If I restart Solid Queue (```rake solid_queue:start```) then the jobs are immediately worked.

This happens with both recurring jobs as well as jobs that are "perform_later".

Starting the solid queue looks all good and there aren't any subsequent log items that indicate any issues.

```ruby
cc@Mac-mini funstuff % rake solid_queue:start
[SolidQueue] Starting Dispatcher(pid=76984, hostname=Mac-mini.local, metadata={:polling_interval=>1, :batch_size=>500, :concurrency_maintenance_interval=>600, :recurring_schedule=>{:"Expire subs"=>{:schedule=>"every day at 00:01", :class_name=>"ExpireSubsJob", :arguments=>[]}, :send_notifications_subs_expired=>{:schedule=>"every day at 00:15", :class_name=>"SendSubsExpirationNotificationJob", :arguments=>[]}, :send_notifications_subs_expiring=>{:schedule=>"every day at 10:00am", :class_name=>"SendSubsExpiringIn7DaysEmailJob", :arguments=>[]}, :"Send new posts email"=>{:schedule=>"every weekday at 5:00, 8:00, 11:00, 13:00, 15:00", :class_name=>"SendNewPostsEmailJob", :arguments=>[]}, :"Identify posts"=>{:schedule=>"every hour at minute 5", :class_name=>"IdentifyPostsJob", :arguments=>[]}, :"Add posts to Profiles"=>{:schedule=>"every 10 minutes", :class_name=>"ProcessNewPostsToProfilesJob", :arguments=>[]}, :"Destroy incomplete Posts"=>{:schedule=>"every day at 7:00am", :class_name=>"CleanUpPostsJob", :arguments=>[]}}})
[SolidQueue] Starting Worker(pid=76985, hostname=Mac-mini.local, metadata={:polling_interval=>1, :queues=>"*", :thread_pool_size=>3})
```

The only setting in my `development.rb`:
config.active_job.queue_adapter = :solid_queue

Solid Queue: 0.3.0
Rails: 7.1.3.2

**Comment by rosa** [comment]
Hey @carsoncole, sorry about that! Could you share a bit more about your DB setup? Also, could you try setting this: 
```ruby
config.solid_queue.silence_polling = false
```
And then starting `solid_queue:start` again? That might give us more clues about what's going on.

**Comment by ekampp** [comment]
I was seeing the same problem. Disabling polling silence seems to trigger it to work properly.

**Comment by carsoncole** [comment]
@rosa Overnight, jobs stopped executing again. I set `silence_polling = false`. I've included the logs at the moment a job was created and enqueued. 

```ruby
 SolidQueue::ScheduledExecution Pluck (3.0ms)  SELECT "solid_queue_scheduled_executions"."job_id" FROM "solid_queue_scheduled_executions" WHERE "solid_queue_scheduled_executions"."scheduled_at" <= $1 ORDER BY "solid_queue_scheduled_executions"."scheduled_at" ASC, "solid_queue_scheduled_executions"."priority" ASC, "solid_queue_scheduled_executions"."job_id" ASC LIMIT $2 FOR UPDATE SKIP LOCKED  [["scheduled_at", "2024-04-11 15:19:59.498234"], ["LIMIT", 500]]

  TRANSACTION (0.1ms)  COMMIT
[ActiveJob]   TRANSACTION (0.2ms)  BEGIN
[ActiveJob]   SolidQueue::Job Create (2.5ms)  INSERT INTO "solid_queue_jobs" ("queue_name", "class_name", "arguments", "priority", "active_job_id", "scheduled_at", "finished_at", "concurrency_key", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"  [["queue_name", "default"], ["class_name", "ProcessNewJobsToProfilesJob"], ["arguments", "{\"job_class\":\"ProcessNewJobsToProfilesJob\",\"job_id\":\"5fc05678-dbf5-45e6-81d6-f925734589f5\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"Pacific Time (US \\u0026 Canada)\",\"enqueued_at\":\"2024-04-11T15:20:00.008251000Z\",\"scheduled_at\":\"2024-04-11T15:20:00.008202000Z\"}"], ["priority", 0], ["active_job_id", "5fc05678-dbf5-45e6-81d6-f925734589f5"], ["scheduled_at", "2024-04-11 15:20:00.008202"], ["finished_at", nil], ["concurrency_key", "[FILTERED]"], ["created_at", "2024-04-11 15:20:00.008732"], ["updated_at", "2024-04-11 15:20:00.008732"]]
[ActiveJob]   TRANSACTION (0.2ms)  SAVEPOINT active_record_1
[ActiveJob]   SolidQueue::Job Load (0.2ms)  SELECT "solid_queue_jobs".* FROM "solid_queue_jobs" WHERE "solid_queue_jobs"."id" = $1 LIMIT $2  [["id", 907], ["LIMIT", 1]]
[ActiveJob]   SolidQueue::ReadyExecution Create (0.7ms)  INSERT INTO "solid_queue_ready_executions" ("job_id", "queue_name", "priority", "created_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["job_id", 907], ["queue_name", "default"], ["priority", 0], ["created_at", "2024-04-11 15:20:00.017665"]]
[ActiveJob]   TRANSACTION (0.1ms)  RELEASE SAVEPOINT active_record_1
[ActiveJob]   Log Create (0.4ms)  INSERT INTO "logs" ("status", "log_class", "class_id", "message", "request", "response_code", "source_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"  [["status", 0], ["log_class", "ProcessNewJobsToProfilesJob"], ["class_id", nil], ["message", "Job #5fc0567 enqueued"], ["request", nil], ["response_code", nil], ["source_id", nil], ["created_at", "2024-04-11 15:20:00.020842"], ["updated_at", "2024-04-11 15:20:00.020842"]]
[ActiveJob]   ↳ app/jobs/application_job.rb:9:in `block in <class:ApplicationJob>'
[ActiveJob] Enqueued ProcessNewJobsToProfilesJob (Job ID: 5fc05678-dbf5-45e6-81d6-f925734589f5) to SolidQueue(default)
  SolidQueue::Job Load (0.1ms)  SELECT "solid_queue_jobs".* FROM "solid_queue_jobs" WHERE "solid_queue_jobs"."id" = $1 LIMIT $2  [["id", 907], ["LIMIT", 1]]
  SolidQueue::RecurringExecution Create (0.6ms)  INSERT INTO "solid_queue_recurring_executions" ("job_id", "task_key", "run_at", "created_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["job_id", 907], ["task_key", "[FILTERED]"], ["run_at", "2024-04-11 15:20:00"], ["created_at", "2024-04-11 15:20:00.023454"]]
  TRANSACTION (1.5ms)  COMMIT
  Rendered admin/logs/_log.html.erb (Duration: 0.3ms | Allocations: 73)
[ActionCable] Broadcasting to logs: "<turbo-stream action=\"prepend\" target=\"logs\"><template><tr id=\"log_2893\" class=\"border-b\">\n  <td class=\"px-2 py-2 w-16 text-center dark:text-slate-700\">\n    <div class='rounded font-bold text-xs px-2 py-1 bg-blue-200'>INFO</div>\n  </td>\n  <td class=\"px-2 py-2\">\n    ProcessNewJob...
  TRANSACTION (0.2ms)  BEGIN
  SolidQueue::ScheduledExecution Pluck (1.9ms)  SELECT "solid_queue_scheduled_executions"."job_id" FROM "solid_queue_scheduled_executions" WHERE "solid_queue_scheduled_executions"."scheduled_at" <= $1 ORDER BY "solid_queue_scheduled_executions"."scheduled_at" ASC, "solid_queue_scheduled_executions"."priority" ASC, "solid_queue_scheduled_executions"."job_id" ASC LIMIT $2 FOR UPDATE SKIP LOCKED  [["scheduled_at", "2024-04-11 15:20:00.507423"], ["LIMIT", 500]]
  TRANSACTION (0.1ms)  COMMIT
  TRANSACTION (0.3ms)  BEGIN
  SolidQueue::ScheduledExecution Pluck (3.2ms)  SELECT "solid_queue_scheduled_executions"."job_id" FROM "solid_queue_scheduled_executions" WHERE "solid_queue_scheduled_executions"."scheduled_at" <= $1 ORDER BY "solid_queue_scheduled_executions"."scheduled_at" ASC, "solid_queue_scheduled_executions"."priority" ASC, "solid_queue_scheduled_executions"."job_id" ASC LIMIT $2 FOR UPDATE SKIP LOCKED  [["scheduled_at", "2024-04-11 15:20:01.515209"], ["LIMIT", 500]]
```


In the Solid Queue console I do here is the output overnight, which I notice `undefined method `queue_adapter_name' for nil:NilClass`...

```ruby
carsoncole@Carsons-Mac-mini ahoyjob % rake solid_queue:start
[SolidQueue] Starting Dispatcher(pid=90937, hostname=Carsons-Mac-mini.local, metadata={:polling_interval=>1, :batch_size=>500, :concurrency_maintenance_interval=>600, :recurring_schedule=>{:"Expire subscriptions"=>{:schedule=>"every day at 00:01", :class_name=>"ExpireSubscriptionsJob", :arguments=>[]}, :send_notifications_subscriptions_expired=>{:schedule=>"every day at 00:15", :class_name=>"SendSubscriptionExpirationNotificationJob", :arguments=>[]}, :send_notifications_subscriptions_expiring=>{:schedule=>"every day at 10:00am", :class_name=>"SendSubscriptionExpiringIn7DaysEmailJob", :arguments=>[]}, :"Send new jobs email"=>{:schedule=>"every weekday at 5:00, 8:00, 11:00, 13:00, 15:00", :class_name=>"SendNewJobsEmailJob", :arguments=>[]}, :"Identify jobs"=>{:schedule=>"every 30 minutes at minute 5", :class_name=>"IdentifyJobsJob", :arguments=>[]}, :"Add jobs to Profiles"=>{:schedule=>"every 10 minutes", :class_name=>"ProcessNewJobsToProfilesJob", :arguments=>[]}, :"Destroy incomplete Jobs"=>{:schedule=>"every day at 7:00am", :class_name=>"CleanUpJobsJob", :arguments=>[]}, :"Clean up incomplete Jobs"=>{:schedule=>"every 4 hours at minute 45", :class_name=>"CleanUpIncompleteJobs", :arguments=>[]}}})
[SolidQueue] Starting Worker(pid=90938, hostname=Carsons-Mac-mini.local, metadata={:polling_interval=>1, :queues=>"*", :thread_pool_size=>3})
[SolidQueue] undefined method `queue_adapter_name' for nil:NilClass
[SolidQueue] Skipped recurring task Add jobs to Profiles at 2024-04-11 08:20:00 UTC — already dispatched
[SolidQueue] Skipped recurring task Identify jobs at 2024-04-11 08:30:00 UTC — already dispatched
[SolidQueue] Skipped recurring task Identify jobs at 2024-04-11 09:30:00 UTC — already dispatched
[SolidQueue] Skipped recurring task Add jobs to Profiles at 2024-04-11 09:30:00 UTC — already dispatched
[SolidQueue] undefined method `queue_adapter_name' for nil:NilClass
[SolidQueue] undefined method `queue_adapter_name' for nil:NilClass
[SolidQueue] Skipped recurring task Send new jobs email at 2024-04-11 12:00:00 UTC — already dispatched
[SolidQueue] Skipped recurring task Destroy incomplete Jobs at 2024-04-11 14:00:00 UTC — already dispatched
[SolidQueue] Skipped recurring task Add jobs to Profiles at 2024-04-11 14:20:00 UTC — already dispatched
[SolidQueue] Skipped recurring task Identify jobs at 2024-04-11 14:30:00 UTC — already dispatched
```

**Comment by carsoncole** [comment]
Another recurring job just added. It's in the table `solid_queue_recurring_executions` and I see it as entry in `solid_queue_ready_executions`, but in the log I only see the constant query `SELECT "solid_queue_scheduled_executions"` around the time the job is created.

**Comment by carsoncole** [comment]
**database.yml**

```ruby
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ahoyjob_development
```

This may be relevant, I'm using Postgresql for Action Cable

```ruby
development:
  adapter: postgresql

test:
  adapter: test

production:
  adapter: postgresql

```

**Comment by carsoncole** [comment]
Another datapoint is that I have a `Job` class in my app that represents jobs, ie. developer, bus driver etc.

**Comment by carsoncole** [comment]
So through my test case below, I can trigger the ```undefined method `queue_adapter_name' for nil:NilClass``` with an incorrectly named class.

**solid_queue.yml**
```yml
  "Test Job":
    class: Testjob
    schedule: every minute
```

Job file was named `testjob.rb` and the class name was `TestJob`

I've fixed that now and running again to see if that has anything to do with not working jobs.

**Comment by carsoncole** [comment]
It does appear that the `SolidQueue::ReadyExecution` just dies and does not give any indication of why. In my logs it is executing at its interval of 1 second, and then stops. Here in my logs you see it actually finds a record when doing 
```ruby
SolidQueue::ReadyExecution Pluck (2.5ms)  SELECT "solid_queue_ready_executions"."job_id" FROM "solid_queue_ready_executions" ORDER BY "solid_queue_ready_executions"."priority" ASC, "solid_queue_ready_executions"."job_id" ASC LIMIT $1 FOR UPDATE SKIP LOCKED  [["LIMIT", 3]]
```
But then stops. Here is the full log and after the last entry for `SELECT solid_queue_ready_executions` it no longer makes the call.

```ruby
 SolidQueue::Job Load (0.2ms)  SELECT "solid_queue_jobs".* FROM "solid_queue_jobs" WHERE "solid_queue_jobs"."id" = $1 LIMIT $2  [["id", 930], ["LIMIT", 1]]
  SolidQueue::RecurringExecution Create (1.4ms)  INSERT INTO "solid_queue_recurring_executions" ("job_id", "task_key", "run_at", "created_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["job_id", 930], ["task_key", "[FILTERED]"], ["run_at", "2024-04-11 17:50:00"], ["created_at", "2024-04-11 17:50:00.141010"]]
  TRANSACTION (0.4ms)  COMMIT
  Rendered admin/logs/_log.html.erb (Duration: 0.6ms | Allocations: 576)
[ActionCable] Broadcasting to logs: "<turbo-stream action=\"prepend\" target=\"logs\"><template><tr id=\"log_2970\" class=\"border-b\">\n  <td class=\"px-2 py-2 w-16 text-center dark:text-slate-700\">\n    <div class='rounded font-bold text-xs px-2 py-1 bg-blue-200'>INFO</div>\n  </td>\n  <td class=\"px-2 py-2\">\n    ProcessNewJob...
  SolidQueue::Pause Pluck (0.9ms)  SELECT "solid_queue_pauses"."queue_name" FROM "solid_queue_pauses"
  TRANSACTION (0.2ms)  BEGIN
  SolidQueue::ReadyExecution Pluck (2.5ms)  SELECT "solid_queue_ready_executions"."job_id" FROM "solid_queue_ready_executions" ORDER BY "solid_queue_ready_executions"."priority" ASC, "solid_queue_ready_executions"."job_id" ASC LIMIT $1 FOR UPDATE SKIP LOCKED  [["LIMIT", 3]]
  SolidQueue::ClaimedExecution Insert (1.9ms)  INSERT INTO "solid_queue_claimed_executions" ("job_id","process_id","created_at") VALUES (930, 148, CURRENT_TIMESTAMP) RETURNING "id"
  SolidQueue::ClaimedExecution Load (0.4ms)  SELECT "solid_queue_claimed_executions".* FROM "solid_queue_claimed_executions" WHERE "solid_queue_claimed_executions"."job_id" = $1 AND "solid_queue_claimed_executions"."process_id" = $2  [["job_id", 930], ["process_id", 148]]
  SolidQueue::ReadyExecution Delete All (1.3ms)  DELETE FROM "solid_queue_ready_executions" WHERE "solid_queue_ready_executions"."job_id" = $1  [["job_id", 930]]
  TRANSACTION (0.4ms)  COMMIT
  SolidQueue::Pause Pluck (0.8ms)  SELECT "solid_queue_pauses"."queue_name" FROM "solid_queue_pauses"
  TRANSACTION (1.0ms)  BEGIN
  SolidQueue::ReadyExecution Pluck (2.7ms)  SELECT "solid_queue_ready_executions"."job_id" FROM "solid_queue_ready_executions" ORDER BY "solid_queue_ready_executions"."priority" ASC, "solid_queue_ready_executions"."job_id" ASC LIMIT $1 FOR UPDATE SKIP LOCKED  [["LIMIT", 2]]
  TRANSACTION (0.4ms)  COMMIT
  SolidQueue::Job Load (0.8ms)  SELECT "solid_queue_jobs".* FROM "solid_queue_jobs" WHERE "solid_queue_jobs"."id" = $1 LIMIT $2  [["id", 930], ["LIMIT", 1]]
  TRANSACTION (0.2ms)  BEGIN
  SolidQueue::ScheduledExecution Pluck (1.8ms)  SELECT "solid_queue_scheduled_executions"."job_id" FROM "solid_queue_scheduled_executions" WHERE "solid_queue_scheduled_executions"."scheduled_at" <= $1 ORDER BY "solid_queue_scheduled_executions"."scheduled_at" ASC, "solid_queue_scheduled_executions"."priority" ASC, "solid_queue_scheduled_executions"."job_id" ASC LIMIT $2 FOR UPDATE SKIP LOCKED  [["scheduled_at", "2024-04-11 17:50:01.129034"], ["LIMIT", 500]]
  TRANSACTION (0.1ms)  COMMIT
  TRANSACTION (0.2ms)  BEGIN
  SolidQueue::ScheduledExecution Pluck (1.6ms)  SELECT "solid_queue_scheduled_executions"."job_id" FROM "solid_queue_scheduled_executions" WHERE "solid_queue_scheduled_executions"."scheduled_at" <= $1 ORDER BY "solid_queue_scheduled_executions"."scheduled_at" ASC, "solid_queue_scheduled_executions"."priority" ASC, "solid_queue_scheduled_executions"."job_id" ASC LIMIT $2 FOR UPDATE SKIP LOCKED  [["scheduled_at", "2024-04-11 17:50:02.138170"], ["LIMIT", 500]]
```

**Comment by rosa** [comment]
@carsoncole thanks for all these extra details 🙏🏻 @SjoerdL, that's super helpful! I'll try to investigate a bit more today, and see if I can get to to bottom of this 🔍💪🏻

**Comment by carsoncole** [comment]
I got the issue to show itself quickly by changing the threads to 1. To hide the issue longer, increase the number of threads.

```ruby
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 1
```

**Comment by carldr** [comment]
I'm experiencing a similar problem too, and is reliably caused in development mode by saving any Ruby file in my Rails project.  As soon as I do, new jobs are picked up but never finish, and I have to ctrl+c solid queue and re-start it.  If I don't save a file, Solid Queue will continue to work fine for hours.

I've not checked if they actually run or not before getting stuck, I came across this issue while investigating whether I'd setup something up incorrectly, but this seems very similar behaviour to what @SjoerdL is experiencing.

**Comment by ekampp** [comment]
Hey, @rosa, thanks for digging into this one!

**Comment by bebbs** [comment]
I can reproduce this in a personal project in development, presenting exactly the same way as @carldr [describes above](https://github.com/rails/solid_queue/issues/204#issuecomment-2053995621).

**Comment by nzifnab** [comment]
> I'm experiencing a similar problem too, and is reliably caused in development mode by saving any Ruby file in my Rails project. As soon as I do, new jobs are picked up but never finish, and I have to ctrl+c solid queue and re-start it. If I don't save a file, Solid Queue will continue to work fine for hours.
> 
> I've not checked if they actually run or not before getting stuck, I came across this issue while investigating whether I'd setup something up incorrectly, but this seems very similar behaviour to what @SjoerdL is experiencing.

I'm currently able to reproduce doing this exact step. Perform an action in the app that enqueues a job, it executes flawlessly. Save a couple files (I added comments to 3 files and saved them), now that exact same action done in the exact same manner enqueues a job, but it gets stuck in "In Progress Jobs" for some reason.

FWIW I'm running solid_queue using a foreman `Procfile.dev`:

```
web: bundle exec rdbg --command --nonstop --open=vscode --sock_path=tmp/sockets/rdbg.socket -- bundle exec bin/rails server -p 3000
css: bundle exec bin/rails tailwindcss:watch[debug]
worker: if [ "$SKIP_SOLID_QUEUE" != "true" ]; then bundle exec rake solid_queue:start; else sleep 2147483647; fi
```

**Comment by rosa** [comment]
Thanks everyone for the info, and so sorry I haven't been able to work on this one yet. It's the next one on deck once I get #208 out of the way 💪

**Comment by ibrahima** [comment]
Hmm, just to make sure I'm on the same page - is SolidQueue supposed to auto-reload code in development? I remember back in the day Sidekiq did not, but I just checked and it looks like [it has done so for several years](https://github.com/sidekiq/sidekiq/issues/2450) so my knowledge is a bit out of date. But I imagine for a first-party solution it should work more seamlessly anyway.

I feel like I may have experienced something like this but I am not 100% sure.

**Comment by rosa** [comment]
> But I imagine for a first-party solution it should work more seamlessly anyway.

Absolutely, I need to get this fixed 100%  😅  So yes, this is definitely a problem of Solid Queue right now.

**Comment by rosa** [comment]
Thanks again everyone for the patience and the steps to reproduce this, it has been incredibly helpful. I reproduced it without issues thanks to that, and I think I've tracked down the problem to a fix we put in place for code reloading 😅  I think I know how to fix but need to do some more tests and it's getting a bit late over here, hopefully I'll be able to wrap this up tomorrow! 🤞

**Comment by nzifnab** [comment]
Awesome! Thanks for jumping on this rosa, you're a rockstar (And this project is really sweet), it's been bothering me and my team for a little bit now so it's good to see some momentum on this fix!

**Comment by rosa** [comment]
I was wrong with the root cause, it wasn't related to [this fix](https://github.com/rails/solid_queue/pull/82) but to something else. I think #223 should fix this problem. I can't reproduce it anymore with that fix, but if anyone else could test it as well, I'd be super grateful 🙏🏻

**Comment by carsoncole** [comment]
I've been running the "reload-dev-fix" #223 branch and jobs still fail to run after a while and are just enqueued. At one point, "Release claimed job" runs and the jobs are run, but I've got them enqueuing again, and 30 mins have passed so not sure how often the release happens.

`SolidQueue-0.3.0 Prune dead processes (1.9ms)  size: 0
SolidQueue-0.3.0 Prune dead processes (1.6ms)  size: 0
SolidQueue-0.3.0 Release claimed job (11.7ms)  job_id: 1256, process_id: 225
SolidQueue-0.3.0 Release claimed job (6.7ms)  job_id: 1257, process_id: 225
SolidQueue-0.3.0 Release claimed job (4.0ms)  job_id: 1258, process_id: 225
SolidQueue-0.3.0 Release claimed job (3.8ms)  job_id: 1259, process_id: 225
SolidQueue-0.3.0 Release claimed job (3.5ms)  job_id: 1260, process_id: 225`

For me, it's easy to see when the jobs stop running I'm using hooks in ApplicationJob to log every step of the process. This may be helpful for others trying to debug to use.

`  after_enqueue do |job|
    Log.create(message: "Job ##{ job.job_id[0, 7] } enqueued", log_class: job.class, status: :info, queue: job.queue_name)
  end

  before_perform do |job|
    Log.create(message: "Job ##{ job.job_id[0, 7] } started", log_class: job.class, status: :info, queue: job.queue_name)
  end

  after_perform do |job|
    Log.create(message: "Job ##{ job.job_id[0, 7] } completed", log_class: job.class, status: :info, queue: job.queue_name)
  end`

**Comment by rosa** [comment]
Huh, I see! @carsoncole, but does this happen when you modify any code? Or just out of the blue without you doing anything? Wondering if this issue is the same as the one I've attempted to fix or if it's something else 🤔  The bit that I can't explain is why your jobs are released:
```
SolidQueue-0.3.0 Release claimed job (11.7ms)  job_id: 1256, process_id: 225
SolidQueue-0.3.0 Release claimed job (6.7ms)  job_id: 1257, process_id: 225
SolidQueue-0.3.0 Release claimed job (4.0ms)  job_id: 1258, process_id: 225
SolidQueue-0.3.0 Release claimed job (3.8ms)  job_id: 1259, process_id: 225
SolidQueue-0.3.0 Release claimed job (3.5ms)  job_id: 1260, process_id: 225
```
This means something happened to process 225, but it's strange that you didn't get any logs about that, about the process being deregistered... 😕  Did you happen to see if any of the logs lines about 
```
SolidQueue-0.3.0 Prune dead processes (1.6ms)  size: 0
```
had any other `size` than `0`?

**Comment by ekampp** [comment]
I'm also running that branch, and I'm getting this a lot. Probably every 5 or six seconds after I start changing code.

> SolidQueue-0.3.0 Prune dead processes (1.9ms)  size: 0

**Comment by carsoncole** [comment]
I've been running this for a few hours and I don't have any logs indicating a size other than 0.

This log entry is occurring ever 1-2 seconds.

```ruby
SolidQueue-0.3.0 Prune dead processes (5.9ms)  size: 0
```

As for modifying code, I've made multiple code changes across the app during this timeframe.

**Comment by rosa** [comment]
So, to be clear, this is expected: 
> SolidQueue-0.3.0 Prune dead processes (1.9ms) size: 0

But I realised I left a debugging setting there and changed the frequency of the dead processes check to every 2 seconds instead of every `SolidQueue.process_alive_threshold`, which is 5 minutes by default. I'll push a change for that. But in any case, the logs
> SolidQueue-0.3.0 Prune dead processes (1.9ms) size: 0

are expected and don't mean something is wrong. The workers hanging and not processing jobs _do_ mean something is wrong. 

Going to push the change to stop running the process prune every 2 seconds. 

Another question: @carsoncole: is it possible something external to Solid Queue is killing your worker processes? What you describe is different from the error I've fixed 🤔 To be clear, the error I've addressed is:

> I'm experiencing a similar problem too, and is reliably caused in development mode by saving any Ruby file in my Rails project. As soon as I do, new jobs are picked up but never finish, and I have to ctrl+c solid queue and re-start it. If I don't save a file, Solid Queue will continue to work fine for hours.

**Comment by carsoncole** [comment]
I understand on the "Prune dead processes" log entry. Sounds good.

As for the issue of not saving files results in everything working fine, I'll test for that. But as of now, I am changing files and the issue is occurring.

**Comment by rosa** [comment]
Ohhh bummer! And so odd! I couldn't reproduce it anymore with that change, while I could reproduce it consistently without it. I'll keep digging. Thank you so much for your patience 🙏

**Comment by carsoncole** [comment]
I will try creating a barebones new app and see if I can recreate the issue and isolate it from any other code I have.

**Comment by carsoncole** [comment]
I can confirm that the following is correct.

> I'm experiencing a similar problem too, and is reliably caused in development mode by saving any Ruby file in my Rails project. As soon as I do, new jobs are picked up but never finish, and I have to ctrl+c solid queue and re-start it. If I don't save a file, Solid Queue will continue to work fine for hours.

I can't see the pattern as to what file change affects what, as I have different queues, and it'll be just one queue that no longer executes enqueued jobs unless restarted.

**Comment by nzifnab** [comment]
So far in my limited testing, that branch has fixed my issue of code reloading. I'll continue to experiment w/ it; I haven't been testing with it for very long.

**Comment by johnmcdowall** [comment]
This is the full dump of the stack trace that happens in my environment for @rafaelfranca:

- ruby 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]
- Rails 7.1.3.2
- PostgresQL (running in a docker container)

This particular crash happened because I did a db:reset. The dump is too large to paste here, so it's a gist: 

[Stack Dump](https://gist.github.com/johnmcdowall/496be2b8148f956da0c843472fb5d5e2)

**Comment by andyjeffries** [comment]
@rosa I was experiencing the same thing, came here to see what the latest update is and can confirm `reload-dev-fix` appears to fix it for me (at least it's been over an hour since I updated and it hasn't died yet, but normally wouldn't last more than 15-30 minutes)

**Comment by rosa** [comment]
Thanks a lot for letting me know, @andyjeffries and @nzifnab 🙏  I'm going to merge that fix and ship a new version but will keep this one open since it still fails for some people, so I'll keep investigating.

**Comment by johnmcdowall** [comment]
FWIW I have also been using the `reload-dev-fix` branch for around 5 days now, and I haven't seen this issue crop up once!

**Comment by andyjeffries** [comment]
I switched to the newly released version that includes this merged fix since Tuesday May 21 08:50 BST and it's been absolutely fine for me since then too. Awesome fix @rosa, thanks !

**Comment by rosa** [comment]
Hey @carsoncole, are you still experiencing this? I haven't heard any more reports since this fix went live, so I'd like to dig more into your case, because it's very strange. You mentioned: 

> as I have different queues, and it'll be just one queue that no longer executes enqueued jobs unless restarted.

But are these queues run by different workers, all individually? Or multiple queues can be run by the same worker? Just wondering if this might be a priority kind of problem 🤔

**Comment by searls** [comment]
👋 Came to the repo to open a similar issue, which I've been experiencing in local development since January. Until reading this, I was sort of at a loss as to why solid_queue workers would pick stuff up fine at startup and then eventually stop grabbing work—I hadn't considered that it might be due to (some consequence of) class reloading. 

Unfortunately, I'm currently on the released version (0.3.4) and still experiencing this daily in development. I was just about to switch over to running inline or async locally to unblock myself. It's possible that I'm experiencing a _different_ issue leading to the same outcome, but I don't feel well-equipped to debug it (any tips would be appreciated)

**Comment by rosa** [comment]
Ouch, sorry to hear that @searls! I wonder if you could try running the branch in https://github.com/rails/solid_queue/pull/269, not via the Puma plugin or anything, but just directly, and see if that changes anything 🤔  

Do you think your issue happens also due to class reloading or could it be something else? What DB are you using?

**Comment by searls** [comment]
Hi @rosa thank you for replying. I have been running off the branch in #269 since this morning and haven't seen it fail yet, but I'll keep you posted. I was almost sure it was failing again but it turns out that I was seeing a [separate apparent issue](https://discuss.hotwired.dev/t/debugging-turbo-broadcastjob-only-working-with-inline-async/5916?u=searls)

**Comment by rosa** [comment]
Thanks a lot for letting me know, @searls 🙏  Huh, that issue is strange indeed 🤔

**Comment by rosa** [comment]
I'm going to close this one as I haven't heard about it in a long time, and I trust it was fixed with #223.

**Comment by jdblack** [comment]
I'm still seeing this on rails 8.0.1   things work great for a couple days, but then all the jobs stop.   I found that the problem is that  recurring jobs stop automatically running.    Manually kicking off the jobs seems to work,   so   solidqueue as a whole is working. It's just the  recurring jobs that are failing for me



My jobs are triggered by recurring jobs:
![Image](https://github.com/user-attachments/assets/666eda8e-cf8b-4468-b939-b7bf33824ca6)




```
[ActiveJob] [FactProcessorJob] [ff067052-d58e-4ff3-bcb3-eb20820db0d9] Performing FactProcessorJob (Job ID: ff067052-d58e-4ff3-bcb3-eb20820db0d9) from SolidQueue(facts) enqueued at 2025-03-11T08:28:54.421608000Z with arguments: #<GlobalID:0x000000012fc73a00 @uri=#<URI::GID gid://newsapi/Article/2235>>, {"fact" => "The ICC can step in when countries are unwilling or unable to prosecute suspects in the most heinous international crimes, including genocide, war crimes and crimes against humanity, based in The Hague, the Netherlands.", "entities" => ["ICC", "The Hague", "Netherlands"], "date" => "2025-03-11"}
[ActiveJob] [FactProcessorJob] [e0e91084-315c-4011-9978-f3f1592d794a] Performed FactProcessorJob (Job ID: e0e91084-315c-4011-9978-f3f1592d794a) from SolidQueue(facts) in 5237.57ms
[ActiveJob] [FactProcessorJob] [ddc71794-c204-4d2a-be6c-1dad1b440bfe] Performed FactProcessorJob (Job ID: ddc71794-c204-4d2a-be6c-1dad1b440bfe) from SolidQueue(facts) in 5368.84ms
[ActiveJob] [FactProcessorJob] [070371fe-ee45-4cb3-907f-ea8d83c06396] Performed FactProcessorJob (Job ID: 070371fe-ee45-4cb3-907f-ea8d83c06396) from SolidQueue(facts) in 5993.75ms
[ActiveJob] [FactProcessorJob] [ff067052-d58e-4ff3-bcb3-eb20820db0d9] Performed FactProcessorJob (Job ID: ff067052-d58e-4ff3-bcb3-eb20820db0d9) from SolidQueue(facts) in 1007.55ms
[ActiveJob] [FactProcessorJob] [3abf711a-e4ce-4740-8d32-f3847900cab1] Performing FactProcessorJob (Job ID: 3abf711a-e4ce-4740-8d32-f3847900cab1) from SolidQueue(facts) enqueued at 2025-03-11T08:28:54.430069000Z with arguments: #<GlobalID:0x000000012fd983e0 @uri=#<URI::GID gid://newsapi/Article/2235>>, {"fact" => "President Ferdinand Marcos Jr., who succeeded Duterte in 2022 and became entangled in a bitter political dispute with the former president, has decided not to rejoin the global court.", "entities" => ["Ferdinand Marcos Jr.", "Duterte"], "date" => "2025-03-11"}
[ActiveJob] [FactProcessorJob] [3abf711a-e4ce-4740-8d32-f3847900cab1] Performed FactProcessorJob (Job ID: 3abf711a-e4ce-4740-8d32-f3847900cab1) from SolidQueue(facts) in 1076.2ms
[ActiveJob] [FactProcessorJob] [539d66ca-b074-49a8-a303-4e25975f2b26] Performed FactProcessorJob (Job ID: 539d66ca-b074-49a8-a303-4e25975f2b26) from SolidQueue(facts) in 5585.38ms
[ActiveJob] [FactProcessorJob] [1365a3c0-01b2-4092-af75-ec552bc805f6] Performed FactProcessorJob (Job ID: 1365a3c0-01b2-4092-af75-ec552bc805f6) from SolidQueue(facts) in 5392.67ms
SolidQueue-1.1.3 Fail claimed jobs (2.3ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.3ms)  size: 0
SolidQueue-1.1.3 Fail claimed jobs (0.4ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.3ms)  size: 0
SolidQueue-1.1.3 Shutdown Worker (26.3ms)  pid: 26824, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-fa36496b8ca1de2610b4", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Shutdown Worker (35.6ms)  pid: 26825, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-dccd502c3cf1ab13501c", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Replaced terminated Worker (22.5ms)  pid: 26825, status: 0, pid_from_status: 26825, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-dccd502c3cf1ab13501c"
SolidQueue-1.1.3 Replaced terminated Worker (18.4ms)  pid: 26824, status: 0, pid_from_status: 26824, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-fa36496b8ca1de2610b4"
SolidQueue-1.1.3 Started Worker (208.5ms)  pid: 27688, hostname: "Jamess-MacBook-Pro.local", process_id: 670, name: "worker-03ae35ec2fdf13ddf302", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Started Worker (219.2ms)  pid: 27689, hostname: "Jamess-MacBook-Pro.local", process_id: 671, name: "worker-528f9121dbe6c6420f97", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Fail claimed jobs (0.4ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.2ms)  size: 0
SolidQueue-1.1.3 Fail claimed jobs (0.2ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.2ms)  size: 0
SolidQueue-1.1.3 Shutdown Worker (23.3ms)  pid: 27688, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-03ae35ec2fdf13ddf302", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Shutdown Worker (21.8ms)  pid: 27689, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-528f9121dbe6c6420f97", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Replaced terminated Worker (20.1ms)  pid: 27689, status: 0, pid_from_status: 27689, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-528f9121dbe6c6420f97"
SolidQueue-1.1.3 Replaced terminated Worker (18.1ms)  pid: 27688, status: 0, pid_from_status: 27688, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-03ae35ec2fdf13ddf302"
SolidQueue-1.1.3 Started Worker (207.5ms)  pid: 27714, hostname: "Jamess-MacBook-Pro.local", process_id: 672, name: "worker-ae0cab48ddf908dcb664", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Started Worker (218.0ms)  pid: 27715, hostname: "Jamess-MacBook-Pro.local", process_id: 673, name: "worker-203474d51acc43905a8c", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Fail claimed jobs (1.3ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.7ms)  size: 0
SolidQueue-1.1.3 Fail claimed jobs (0.7ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.6ms)  size: 0
SolidQueue-1.1.3 Shutdown Worker (22.0ms)  pid: 27714, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-ae0cab48ddf908dcb664", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Shutdown Worker (21.2ms)  pid: 27715, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-203474d51acc43905a8c", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Replaced terminated Worker (21.2ms)  pid: 27715, status: 0, pid_from_status: 27715, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-203474d51acc43905a8c"
SolidQueue-1.1.3 Replaced terminated Worker (18.4ms)  pid: 27714, status: 0, pid_from_status: 27714, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-ae0cab48ddf908dcb664"
SolidQueue-1.1.3 Started Worker (208.2ms)  pid: 27735, hostname: "Jamess-MacBook-Pro.local", process_id: 674, name: "worker-7f01542d6c2f719be0dd", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Started Worker (216.6ms)  pid: 27736, hostname: "Jamess-MacBook-Pro.local", process_id: 675, name: "worker-fbbb599e0007aee96111", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Fail claimed jobs (0.4ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.2ms)  size: 0
SolidQueue-1.1.3 Fail claimed jobs (0.2ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.2ms)  size: 0
SolidQueue-1.1.3 Shutdown Worker (5.9ms)  pid: 27735, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-7f01542d6c2f719be0dd", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Shutdown Worker (5.0ms)  pid: 27736, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-fbbb599e0007aee96111", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Replaced terminated Worker (7.4ms)  pid: 27736, status: 0, pid_from_status: 27736, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-fbbb599e0007aee96111"
SolidQueue-1.1.3 Replaced terminated Worker (5.2ms)  pid: 27735, status: 0, pid_from_status: 27735, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-7f01542d6c2f719be0dd"
SolidQueue-1.1.3 Started Worker (53.1ms)  pid: 27769, hostname: "Jamess-MacBook-Pro.local", process_id: 676, name: "worker-72179f68f8974e6f4da5", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Started Worker (54.5ms)  pid: 27770, hostname: "Jamess-MacBook-Pro.local", process_id: 677, name: "worker-f53ccfc71a18d5bf043a", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Fail claimed jobs (0.6ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.2ms)  size: 0
SolidQueue-1.1.3 Fail claimed jobs (0.2ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.9ms)  size: 0
SolidQueue-1.1.3 Shutdown Worker (24.5ms)  pid: 27769, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-72179f68f8974e6f4da5", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Shutdown Worker (23.9ms)  pid: 27770, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-f53ccfc71a18d5bf043a", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Replaced terminated Worker (24.2ms)  pid: 27770, status: 0, pid_from_status: 27770, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-f53ccfc71a18d5bf043a"
SolidQueue-1.1.3 Replaced terminated Worker (19.3ms)  pid: 27769, status: 0, pid_from_status: 27769, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-72179f68f8974e6f4da5"
SolidQueue-1.1.3 Started Worker (236.3ms)  pid: 34308, hostname: "Jamess-MacBook-Pro.local", process_id: 678, name: "worker-9431a8c840e41e50150c", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Started Worker (250.3ms)  pid: 34309, hostname: "Jamess-MacBook-Pro.local", process_id: 679, name: "worker-6c26b413f3c0ed6448e2", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Fail claimed jobs (3.0ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (2.3ms)  size: 0
SolidQueue-1.1.3 Fail claimed jobs (8.0ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (3.7ms)  size: 0
SolidQueue-1.1.3 Shutdown Worker (21.1ms)  pid: 34308, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-9431a8c840e41e50150c", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Shutdown Worker (22.1ms)  pid: 34309, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-6c26b413f3c0ed6448e2", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Replaced terminated Worker (23.8ms)  pid: 34309, status: 0, pid_from_status: 34309, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-6c26b413f3c0ed6448e2"
SolidQueue-1.1.3 Replaced terminated Worker (18.2ms)  pid: 34308, status: 0, pid_from_status: 34308, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-9431a8c840e41e50150c"
SolidQueue-1.1.3 Started Worker (210.8ms)  pid: 34329, hostname: "Jamess-MacBook-Pro.local", process_id: 680, name: "worker-374bca9bebca547d691a", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Started Worker (219.7ms)  pid: 34330, hostname: "Jamess-MacBook-Pro.local", process_id: 681, name: "worker-41e7ca1b47f8a2932c8c", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Fail claimed jobs (1.2ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.6ms)  size: 0
SolidQueue-1.1.3 Fail claimed jobs (0.7ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.6ms)  size: 0
SolidQueue-1.1.3 Shutdown Worker (22.7ms)  pid: 34329, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-374bca9bebca547d691a", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Shutdown Worker (22.0ms)  pid: 34330, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-41e7ca1b47f8a2932c8c", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Replaced terminated Worker (18.9ms)  pid: 34330, status: 0, pid_from_status: 34330, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-41e7ca1b47f8a2932c8c"
SolidQueue-1.1.3 Replaced terminated Worker (17.8ms)  pid: 34329, status: 0, pid_from_status: 34329, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-374bca9bebca547d691a"
SolidQueue-1.1.3 Started Worker (214.8ms)  pid: 34346, hostname: "Jamess-MacBook-Pro.local", process_id: 682, name: "worker-a5cc75e219f4040447a7", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Started Worker (230.4ms)  pid: 34347, hostname: "Jamess-MacBook-Pro.local", process_id: 683, name: "worker-f6afa85d5805a07c84b1", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Fail claimed jobs (1.3ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.7ms)  size: 0
SolidQueue-1.1.3 Fail claimed jobs (0.7ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.6ms)  size: 0
SolidQueue-1.1.3 Shutdown Worker (22.5ms)  pid: 34346, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-a5cc75e219f4040447a7", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Shutdown Worker (22.4ms)  pid: 34347, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-f6afa85d5805a07c84b1", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Replaced terminated Worker (6.6ms)  pid: 34347, status: 0, pid_from_status: 34347, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-f6afa85d5805a07c84b1"
SolidQueue-1.1.3 Replaced terminated Worker (4.9ms)  pid: 34346, status: 0, pid_from_status: 34346, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-a5cc75e219f4040447a7"
SolidQueue-1.1.3 Started Worker (366.2ms)  pid: 34365, hostname: "Jamess-MacBook-Pro.local", process_id: 684, name: "worker-dba6363e2deb7957cb08", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Started Worker (373.0ms)  pid: 34366, hostname: "Jamess-MacBook-Pro.local", process_id: 685, name: "worker-8d6296c3bda2bfa26b87", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Fail claimed jobs (0.3ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.2ms)  size: 0
SolidQueue-1.1.3 Fail claimed jobs (0.2ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.2ms)  size: 0
SolidQueue-1.1.3 Shutdown Worker (18.6ms)  pid: 34366, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-8d6296c3bda2bfa26b87", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Shutdown Worker (19.1ms)  pid: 34365, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-dba6363e2deb7957cb08", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Replaced terminated Worker (79.7ms)  pid: 34366, status: 0, pid_from_status: 34366, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-8d6296c3bda2bfa26b87"
SolidQueue-1.1.3 Replaced terminated Worker (18.1ms)  pid: 34365, status: 0, pid_from_status: 34365, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-dba6363e2deb7957cb08"
SolidQueue-1.1.3 Started Worker (228.9ms)  pid: 34440, hostname: "Jamess-MacBook-Pro.local", process_id: 686, name: "worker-5c35a1d9409c8e8dc2d2", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Started Worker (231.3ms)  pid: 34441, hostname: "Jamess-MacBook-Pro.local", process_id: 687, name: "worker-462c60145e7418ddea01", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Fail claimed jobs (1.4ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.6ms)  size: 0
SolidQueue-1.1.3 Fail claimed jobs (0.8ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.7ms)  size: 0
SolidQueue-1.1.3 Shutdown Worker (26.5ms)  pid: 34440, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-5c35a1d9409c8e8dc2d2", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Shutdown Worker (26.4ms)  pid: 34441, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-462c60145e7418ddea01", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Replaced terminated Worker (29.1ms)  pid: 34441, status: 0, pid_from_status: 34441, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-462c60145e7418ddea01"
SolidQueue-1.1.3 Replaced terminated Worker (19.1ms)  pid: 34440, status: 0, pid_from_status: 34440, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-5c35a1d9409c8e8dc2d2"
SolidQueue-1.1.3 Started Worker (219.5ms)  pid: 34462, hostname: "Jamess-MacBook-Pro.local", process_id: 688, name: "worker-368309322b00e4e770ca", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Started Worker (215.1ms)  pid: 34463, hostname: "Jamess-MacBook-Pro.local", process_id: 689, name: "worker-c49365c045b8daa8b36f", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Fail claimed jobs (1.4ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.7ms)  size: 0
SolidQueue-1.1.3 Fail claimed jobs (0.2ms)  job_ids: [], process_ids: []
SolidQueue-1.1.3 Release claimed jobs (0.2ms)  size: 0
SolidQueue-1.1.3 Shutdown Worker (7.7ms)  pid: 34462, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-368309322b00e4e770ca", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Shutdown Worker (6.9ms)  pid: 34463, hostname: "Jamess-MacBook-Pro.local", process_id: nil, name: "worker-c49365c045b8daa8b36f", polling_interval: 1, queues: "facts", thread_pool_size: 5
SolidQueue-1.1.3 Replaced terminated Worker (6.3ms)  pid: 34463, status: 0, pid_from_status: 34463, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-c49365c045b8daa8b36f"
SolidQueue-1.1.3 Replaced terminated Worker (5.5ms)  pid: 34462, status: 0, pid_from_status: 34462, signaled: false, stopsig: nil, termsig: nil, hostname: "Jamess-MacBook-Pro.local", name: "worker-368309322b00e4e770ca"
SolidQueue-1.1.3 Started Worker (66.1ms)  pid: 34570, hostname: "Jamess-MacBook-Pro.local", process_id: 690, name: "worker-32077e52e793937fd70b", polling_interval: 1, queues: "*", thread_pool_size: 5
SolidQueue-1.1.3 Started Worker (80.2ms)  pid: 34569, hostname: "Jamess-MacBook-Pro.local", process_id: 691, name: "worker-f0fd04453d3a18fe3b4f", polling_interval: 1, queues: "facts", thread_pool_size: 5
Started GET "/jobs/applications/newsapi/failed/jobs?server_id=solid_queue" for ::1 at 2025-03-12 16:19:12 +0700
Processing by MissionControl::Jobs::JobsController#index as HTML
  Parameters: {"server_id" => "solid_queue", "application_id" => "newsapi", "status" => "failed"}
Filter chain halted as :authenticate_by_http_basic rendered or redirected
Completed 401 Unauthorized in 5ms (ActiveRecord: 0.0ms (0 queries, 0 cached) | GC: 0.0ms)


Started GET "/jobs/applications/newsapi/failed/jobs?server_id=solid_queue" for ::1 at 2025-03-12 16:19:16 +0700
Processing by MissionControl::Jobs::JobsController#index as HTML
  Parameters: {"server_id" => "solid_queue", "application_id" => "newsapi", "status" => "failed"}
  Rendered layout /usr/local/lib/ruby/gems/3.4.0/gems/mission_control-jobs-1.0.1/app/views/layouts/mission_control/jobs/application.html.erb (Duration: 54.1ms | GC: 4.2ms)
Completed 200 OK in 191ms (Views: 54.7ms | ActiveRecord: 9.7ms (21 queries, 2 cached) | GC: 9.8ms)


Started GET "/assets/mission_control/jobs/bulma.min-a4df5423.css" for ::1 at 2025-03-12 16:19:16 +0700
Started GET "/assets/turbo.min-fae85750.js" for ::1 at 2025-03-12 16:19:16 +0700
Started GET "/assets/stimulus.min-4b1e420e.js" for ::1 at 2025-03-12 16:19:16 +0700
Started GET "/jobs/applications/newsapi/blocked/jobs?server_id=solid_queue" for ::1 at 2025-03-12 16:19:19 +0700
Processing by MissionControl::Jobs::JobsController#index as HTML
  Parameters: {"server_id" => "solid_queue", "application_id" => "newsapi", "status" => "blocked"}
Filter chain halted as :authenticate_by_http_basic rendered or redirected
Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms (0 queries, 0 cached) | GC: 0.0ms)


Started GET "/jobs/applications/newsapi/blocked/jobs?server_id=solid_queue" for ::1 at 2025-03-12 16:19:19 +0700
Processing by MissionControl::Jobs::JobsController#index as HTML
  Parameters: {"server_id" => "solid_queue", "application_id" => "newsapi", "status" => "blocked"}
  Rendered layout /usr/local/lib/ruby/gems/3.4.0/gems/mission_control-jobs-1.0.1/app/views/layouts/mission_control/jobs/application.html.erb (Duration: 6.6ms | GC: 0.0ms)
Completed 200 OK in 16ms (Views: 6.3ms | ActiveRecord: 1.9ms (13 queries, 1 cached) | GC: 1.3ms)


Started GET "/jobs/applications/newsapi/finished/jobs?server_id=solid_queue" for ::1 at 2025-03-12 16:19:19 +0700
Processing by MissionControl::Jobs::JobsController#index as HTML
  Parameters: {"server_id" => "solid_queue", "application_id" => "newsapi", "status" => "finished"}
Filter chain halted as :authenticate_by_http_basic rendered or redirected
Completed 401 Unauthorized in 0ms (ActiveRecord: 0.0ms (0 queries, 0 cached) | GC: 0.0ms)


Started GET "/jobs/applications/newsapi/finished/jobs?server_id=solid_queue" for ::1 at 2025-03-12 16:19:20 +0700
Processing by MissionControl::Jobs::JobsController#index as HTML
  Parameters: {"server_id" => "solid_queue", "application_id" => "newsapi", "status" => "finished"}
  Rendered layout /usr/local/lib/ruby/gems/3.4.0/gems/mission_control-jobs-1.0.1/app/views/layouts/mission_control/jobs/application.html.erb (Duration: 28.5ms | GC: 0.0ms)
Completed 200 OK in 156ms (Views: 28.3ms | ActiveRecord: 9.3ms (76 queries, 62 cached) | GC: 16.8ms)


Started GET "/jobs/applications/newsapi/scheduled/jobs?server_id=solid_queue" for ::1 at 2025-03-12 16:19:22 +0700
Processing by MissionControl::Jobs::JobsController#index as HTML
  Parameters: {"server_id" => "solid_queue", "application_id" => "newsapi", "status" => "scheduled"}
Filter chain halted as :authenticate_by_http_basic rendered or redirected
Completed 401 Unauthorized in 0ms (ActiveRecord: 0.0ms (0 queries, 0 cached) | GC: 0.0ms)


Started GET "/jobs/applications/newsapi/scheduled/jobs?server_id=solid_queue" for ::1 at 2025-03-12 16:19:22 +0700
Processing by MissionControl::Jobs::JobsController#index as HTML
  Parameters: {"server_id" => "solid_queue", "application_id" => "newsapi", "status" => "scheduled"}
  Rendered layout /usr/local/lib/ruby/gems/3.4.0/gems/mission_control-jobs-1.0.1/app/views/layouts/mission_control/jobs/application.html.erb (Duration: 5.9ms | GC: 0.0ms)
Completed 200 OK in 14ms (Views: 5.8ms | ActiveRecord: 1.4ms (13 queries, 1 cached) | GC: 0.0ms)


Started GET "/jobs/applications/newsapi/in_progress/jobs?server_id=solid_queue" for ::1 at 2025-03-12 16:19:25 +0700
Processing by MissionControl::Jobs::JobsController#index as HTML
  Parameters: {"server_id" => "solid_queue", "application_id" => "newsapi", "status" => "in_progress"}
Filter chain halted as :authenticate_by_http_basic rendered or redirected
Completed 401 Unauthorized in 0ms (ActiveRecord: 0.0ms (0 queries, 0 cached) | GC: 0.0ms)


Started GET "/jobs/applications/newsapi/in_progress/jobs?server_id=solid_queue" for ::1 at 2025-03-12 16:19:25 +0700
Processing by MissionControl::Jobs::JobsController#index as HTML
  Parameters: {"server_id" => "solid_queue", "application_id" => "newsapi", "status" => "in_progress"}
  Rendered layout /usr/local/lib/ruby/gems/3.4.0/gems/mission_control-jobs-1.0.1/app/views/layouts/mission_control/jobs/application.html.erb (Duration: 14.6ms | GC: 0.0ms)
Completed 200 OK in 19ms (Views: 14.4ms | ActiveRecord: 1.7ms (13 queries, 1 cached) | GC: 0.0ms)


Started GET "/jobs/applications/newsapi/scheduled/jobs?server_id=solid_queue" for ::1 at 2025-03-12 16:19:27 +0700
Processing by MissionControl::Jobs::JobsController#index as HTML
  Parameters: {"server_id" => "solid_queue", "application_id" => "newsapi", "status" => "scheduled"}
  Rendered layout /usr/local/lib/ruby/gems/3.4.0/gems/mission_control-jobs-1.0.1/app/views/layouts/mission_control/jobs/application.html.erb (Duration: 11.1ms | GC: 0.6ms)
Completed 200 OK in 14ms (Views: 11.0ms | ActiveRecord: 1.3ms (13 queries, 1 cached) | GC: 0.6ms)


Started GET "/jobs/applications/newsapi/recurring_tasks?server_id=solid_queue" for ::1 at 2025-03-12 16:19:29 +0700
Processing by MissionControl::Jobs::RecurringTasksController#index as HTML
  Parameters: {"server_id" => "solid_queue", "application_id" => "newsapi"}
Filter chain halted as :authenticate_by_http_basic rendered or redirected
Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms (0 queries, 0 cached) | GC: 0.0ms)


Started GET "/jobs/applications/newsapi/recurring_tasks?server_id=solid_queue" for ::1 at 2025-03-12 16:19:29 +0700
Processing by MissionControl::Jobs::RecurringTasksController#index as HTML
  Parameters: {"server_id" => "solid_queue", "application_id" => "newsapi"}
  Rendered layout /usr/local/lib/ruby/gems/3.4.0/gems/mission_control-jobs-1.0.1/app/views/layouts/mission_control/jobs/application.html.erb (Duration: 46.2ms | GC: 1.5ms)
Completed 200 OK in 61ms (Views: 45.8ms | ActiveRecord: 1.1ms (10 queries, 0 cached) | GC: 2.4ms)


Started GET "/jobs/applications/newsapi/workers?server_id=solid_queue" for ::1 at 2025-03-12 16:19:31 +0700
Processing by MissionControl::Jobs::WorkersController#index as HTML
  Parameters: {"server_id" => "solid_queue", "application_id" => "newsapi"}
  Rendered layout /usr/local/lib/ruby/gems/3.4.0/gems/mission_control-jobs-1.0.1/app/views/layouts/mission_control/jobs/application.html.erb (Duration: 33.7ms | GC: 0.4ms)
Completed 200 OK in 36ms (Views: 32.7ms | ActiveRecord: 1.5ms (10 queries, 0 cached) | GC: 0.4ms)


Started GET "/jobs/applications/newsapi/finished/jobs?server_id=solid_queue" for ::1 at 2025-03-12 16:19:32 +0700
Processing by MissionControl::Jobs::JobsController#index as HTML
  Parameters: {"server_id" => "solid_queue", "application_id" => "newsapi", "status" => "finished"}
  Rendered layout /usr/local/lib/ruby/gems/3.4.0/gems/mission_control-jobs-1.0.1/app/views/layouts/mission_control/jobs/application.html.erb (Duration: 113.2ms | GC: 69.4ms)
Completed 200 OK in 218ms (Views: 106.6ms | ActiveRecord: 12.8ms (76 queries, 62 cached) | GC: 82.2ms)

```

**Comment by rosa** [comment]
Hey @jdblack, that seems like a different issue... 🤔  Unfortunately the logs alone don't offer a lot of clues. Did your computer go to sleep or something in between that?

**Comment by jdblack** [comment]
> Did your computer go to sleep or something in between that?

Yes. I think that is it!  Thanks!

**Comment by kirley** [comment]
I just upgraded from 1.2.1 to 1.2.2 and I think this bug is back.   When I downgrade to 1.2.1 the worker persists through code changes in development, but with 1.2.2 the workers stop processing jobs after a file is saved in the Rails app.

**Comment by justindoody** [comment]
> I just upgraded from 1.2.1 to 1.2.2 and I think this bug is back. When I downgrade to 1.2.1 the worker persists through code changes in development, but with 1.2.2 the workers stop processing jobs after a file is saved in the Rails app.

In case anyone else stumbles upon this thread while debugging instead of the other like I did it appears resolved in `1.2.3` per https://github.com/rails/solid_queue/pull/672 (and confirmed by my own testing of `1.2.3`)

**Comment by cilim** [comment]
Continuing suggestions for anyone that stumbles upon this bug. Had the same issue. Our solution was increasing the container RAM size from 512MB to 1024MB.

**Comment by andyjeffries** [comment]
Has that definitely fixed it @cilim ? This was happening on my machine with 64GB of RAM and not in a container. It also only happened in development mode. Anyway, might want to check your side that it's definitely fixed and not just delayed.

**Comment by rosa** [comment]
Huh, yes, this bug was reintroduced in 1.2.2, then fixed in 1.2.3. It was something happening in development only, and should be fixed from version 1.2.3.

**Comment by cilim** [comment]
Thanks @andyjeffries! After a week of testing solid_queue, I woke up and found the container in zombie mode every morning. After deploying the RAM increase yesterday, the container was working ok this morning. But yeah, maybe the issue is just delayed...I'll keep an eye out.
